### ISSUE TITLE
Support monorepos

### ISSUE THREAD

**Issue by simoneb** [nearform-actions/optic-release-automation-action#177]
It would be cool if we could support releasing packages in a monorepo. No specific requirements about how this should work, but there aren't any strong reasons why this _shouldn't work_ either. 

For inspiration, npm cli is a monorepo and is using release-please https://github.com/npm/cli.

A few ideas:

- we don't necessarily have to support the lerna way to do it, meaning, a single command to release all packages in the monorepo. It may be enough, to start with, to have the action work properly in the context of a monorepo, meaning, e.g., that when you want to release one of the package, you specify it in the action's input
- each package being released within the monorepo should create a new github release, because gh releases can be named, so it may make sense that they carry the name of the package that was released, for example

**Comment by guilhermelimak** [comment]
I just listed some of the things we should decide before moving forward with the implementation. There are probably more things to consider so this list will probably be updated later as we think more about it.

  1. Allow users to set a root folder for packages as action input
     - Should we allow users to list the packages or do we assume every folder inside the packages directory is a package?
     - Would there be a reason to have multiple root folders for packages?
  2. How's the release process going to work? 
     - Should the user manually run a release for each package?
     - Should the user release all the packages at once so they have synced versions (like babel I think)?
     - Should we check the packages that have changes and release only those?
     - Should we have the previous 3 controlled by an option the user can choose from?
  3. Should we detect which packages were changed based on the files touched by the commits added to the release?
  4. Research a bit how to include only a specific package in the github release
     - Should be relatively simple I think, maybe we can use the upload artifact action?
  5. How do we deal with the build command for each package?
     - Should we accept an object mapping the commands to the packages?
     - Should the user pass the build command when running the release and have a default such as `npm build`? (this only if user will run each release manually)
  6. How should we deal with namespaces in package names? Do we need anything special to handle them?
  7. Should we worry about having different npm/optic tokens for each package?

  ### References
  -  https://github.com/pmowrer/semantic-release-monorepo

**Comment by simoneb** [comment]
I think we should take a step forward and see how others are doing some these things:

1. this is up to us to decide, initially I would go with something simple, e.g. let the user select the folder either writing it in the action inputs or selecting from a list. the list could be populated
2. this is also for us to decide. again I would go with something simple, otherwise we're stepping into the real of monorepo tools such as lerna, so no, I wouldn't do any of those more advanced things, but rather simply "support" monorepos, not have full-blown support for them, which would include keeping versions in sync, bumping only depending on whether there were changes and so on
3. nope, same as point above
4. eh good point, worth checking how repos doing this handle it
5. it would be ok initially to assume that the commands to run are the same across all packages in the monorepo, for simplicity
6. I don't think so!
7. nope, otherwise it'd be a nightmare to handle

**Comment by simoneb** [comment]
We're not going to have this for the time being.
