### ISSUE TITLE
Can't release a newly created package with provenance

### ISSUE THREAD

**Issue by simoneb** [nearform-actions/optic-release-automation-action#301]
It looks like newly created packages cannot be published with this action and provenance enabled. 

See the output of this build which explains why: https://github.com/nearform/fastify-jwt-jwks/actions/runs/4993014295/jobs/8941522625

**Comment by AlanSl** [comment]
🤔 Optic already does some logic to check on whether the package is already on NPM, in `allowNpmPublish`, as part of the check for whether this specific version already exists. We could tweak it to ignore the provenance flag in the `!packageName` condition (maybe logging something in the output), so people can just set `provenance: true` once and not need to change their release config for their first release?

Or maybe this is just something to document?

Though I feel like it'd be nicer if our default config could be something where you can just set it once when first setting up a project and it'll just work and (usually) not need to go in and change.

**Comment by AlanSl** [comment]
Thinking about this again after the discussion this morning - is the underlying issue that on NPM "By default, scoped packages are published with private visibility" (something I often forget, and I'm sure others do too)?

I think we can infer that, if someone has set provenance as true, they must want the package to be published publicly, therefore, if provenance is true but we saw that the package isn't already on NPM, we should simply add `--access public` to the flags when the script runs `npm publish`?

**Comment by simoneb** [comment]
@AlanSl that's the thinking that I was getting to too. Before doing this change though, I would:

1. make extra sure by reading the docs that provenance really is only for public packages, because I'm really not sure about this. If it is now, can we be certain that it will be in the future? I mean setting a package's visibility as public on behalf of the user is a BIG implication and if we do it, we must be extremely confident that that's the right thing to do
2. in case we go with that option, we should make it very visible in the docs of the action that this is what we'll do if provenance is enabled

In case we decide that the above is not a sensible decision, we may consider adding an additional input to the action, called indeed `access`, and we let users know that this needs to be set to `public` if they want to publish a public package with provenance enabled. Not great from a user's perspective to have to do 2 things but I'd be conservative if we're not sure.

**Comment by AlanSl** [comment]
> setting a package's visibility as public on behalf of the user is a BIG implication and if we do it, we must be extremely confident that that's the right thing to do

100% agree.

How does Optic handles the first publish of a scoped package that should be public (without/before provenance)? 

IIRC when I used it with my package the first time (using Optic as it was without provenance support), it failed and I couldn't find any way to set access to public within Optic, so to save time since it wasn't my focus I just did `npm publish --access public` from the command line, then used Optic after.

What was the recommended workflow here? Should we have an explicit public / private flag in the YML maybe or a checkbox in the action button?

**Comment by AlanSl** [comment]
I'd missed that [the original package in question](https://github.com/nearform/fastify-jwt-jwks/) `fastify-jwt-jwks` was unscoped. It does appear to be [impossible for unscoped packages to published as private/restricted](https://docs.npmjs.com/about-scopes#scopes-and-package-visibility):

> ## Scopes and package visibility
> 
> - Unscoped packages are always public.
> - [Private packages](https://docs.npmjs.com/about-private-packages) are always scoped.
> - Scoped packages are private by default; you must pass a command-line flag when publishing to make them public.

...and from what I saw of the implementation of when NPM throws this error, it's based on some `opts.access` that comes from explicit options or the published package state. So it does seem like it should be both possible and safe to add a small bit of provenance-specific logic to add `--access public` just once in the specific case of a never-published unscoped package, where the `--access public` flag is in theory redundant and doesn't change the package's status, but (need to test this) will stop the NPM error from throwing.

I'll do some testing publishing unscoped packages to verify this.

**Comment by simoneb** [comment]
Thanks @AlanSl for looking more closely into this. Indeed if we conclude that it's safe to add access=public automatically because there's no way we could make a package public that's not intended to be public, then I'd go with that
